# Generated by Django 3.0.7 on 2021-09-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tag_set',
            field=models.ManyToManyField(related_name='product', to='product.Category'),
        ),
    ]
