# Generated by Django 3.0.7 on 2021-09-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingadress',
            name='pincode',
            field=models.IntegerField(),
        ),
    ]
