# Generated by Django 3.0.7 on 2021-09-27 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_auto_20210927_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingadress',
            old_name='user',
            new_name='buyer',
        ),
    ]
